### ISSUE TITLE
Remove snap handling logic

### ISSUE THREAD

**Issue by stgraber** [cyphar/incus#8]
As Incus is extremely unlikely to ever be packaged as a snap, with it being a fork of LXD and LXD itself needing a lot of special logic and exceptions to function as a snap. We can simplify the code a fair bit by removing the snap-handling codepaths.

**Comment by UtahDave** [comment]
I'm so happy to hear there will be no snap packages! Dealing with the snaps was such a pain and actually caused my only outage with an LXD cluster. One of the cluster members couldn't update with snap and stopped working

**Comment by stgraber** [comment]
I think ideally, the project shouldn't be providing any packages itself. It should be handled by distros or by third parties who can provide some amount of support on their packages.

The cluster upgrade issue won't really go away though, you'll still have to upgrade all machines at once for the daemon to unstick and come back online. The packaging format used to do that isn't terribly relevant. The main issue with snaps there was that most users didn't know of `--hold` or other options to only refresh the snap when one actually wants it to and is ready to handle the downtime.

**Comment by UtahDave** [comment]
We left packaging up to the distros and third parties for Salt early on. It wasn't too long that we took all packaging in house because updates were so inconsistent and we were having to refer bug reports to the packagers who were often not very responsive.

Hopefully Incus will be simpler to package and the distros will do a good job.

**Comment by stgraber** [comment]
Yeah, that shouldn't be too bad seeing how we have distros covering the full sprectrum of APK, DEB, RPM and EBUILD packaging already for LXD, should be pretty easy to reuse with Incus.

**Comment by cyphar** [comment]
I can play around with doing a multi-distro package using OBS (since I already do the packaging for LXD on openSUSE). If you want to figure out a way for the packaging scripts to be maintained as part of the repo, that might be a little bit more difficult but I'm sure we can work something out.

**Comment by stgraber** [comment]
Nah, I tend to dislike packaging being part of the upstream repo, it's better tracked separately in its own repo.

**Comment by Lillecarl** [comment]
@UtahDave considering what Salt is doing with packaging for the 3007 release I'm convinced leaving it up to the distros is the right move.

**Comment by tarruda** [comment]
> I think ideally, the project shouldn't be providing any packages itself. It should be handled by distros or by third parties who can provide some amount of support on their packages.

Would it be viable refactoring Incus so that most of its components run inside a container? If I'm not mistaken, that is similar to how kubernetes runs some of core services and it can potentially simplify packaging by distributions.

Incus could be a lightweight shim daemon that listens on a socket and forwards all API calls to the real daemon running in a privileged container (which also contains every other dependency needed by Incus, such as a compatible qemu binary).

**Comment by stgraber** [comment]
Well, at that point you're re-inventing snaps as that's exactly what they are. Snaps are some kind of privileged container (uses mount namespace primarily) with some amount of sandboxing (apparmor, seccomp) which allows running a different root filesystem and files from the host system, allowing you to bundle all your dependencies.

In practice, Incus doesn't have that many dependencies and it's also not overly strict about the particular version of those.
We've been going for years with LXD packaged natively in a variety of distros without too many issues there, so I suspect the same will be true with Incus.

There will likely be some "fatter" packages available, basically packages that also bundle a custom qemu, edk2, liblxc, ...
That's not an approach that Linux distributions usually allow in their repositories, but that's a viable option as an external repository for those who want a more tightly controlled and validated solution.

**Comment by smacdonald-parallelz** [comment]
I have a use case that requires I use LXC containers on ARM machines with selinux enabled and apparmor disabled. This fork looks like a promising way for me to get the functionality I need.

**Comment by stgraber** [comment]
SELinux would likely need some work as while underlying lxc supports it, you still need a bunch of tooling to level everything.

**Comment by pachulo** [comment]
Hi @stgraber,

Out of curiosity: I thought that using the LXD snap was "more secure", at least on a system with Ubuntu's kernel patches & AppArmor profiles, than running it without any sandbox, as happens when installed via a classic distro package, like the `.deb` on Debian, for example. So, was I wrong into assuming that?

Thanks!

**Comment by freeekanayaka** [comment]
@pachulo my personal 2 cents: the thing that I dislike of snaps is that it couples **system** confinement/sandboxing/containerization (e.g. AppArmor) with **packaging** containerization (basically, static builds and/or a private "shared" libs tree).

The two concerns can and should be kept separate IMO. You can pretty much add any system sandboxing you want on top `.deb` packages.

I'd like to see some standard tooling for doing that (`systemd` offers a few), and I expect them to emerge and evolve over time.

All that being said, @stgraber is surely in a better position to give a comprehensive answer than me.

**Comment by freeekanayaka** [comment]
BTW, regarding the packaging side, the OCI image format offers a great standard for package-level containerization (static builds and dependency bundling). I wished that projects like flatpak and snap used that instead of re-inventing the wheel.

**Comment by stgraber** [comment]
> Out of curiosity: I thought that using the LXD snap was "more secure", at least on a system with Ubuntu's kernel patches & AppArmor profiles, than running it without any sandbox, as happens when installed via a classic distro package, like the `.deb` on Debian, for example. So, was I wrong into assuming that?

That's true for most snap packages, but isn't for things like LXD or Docker.
The reason is that those packages by their nature require the ability to generate and load apparmor and seccomp profiles.
That same ability allows them to bypass any profile/sandboxing applied to them.

The LXD apparmor and seccomp policies applied by snapd are effectively blank so that it can do whatever it needs to run the instances, in that regard, it's effectively no different than a native distro package.
https://github.com/snapcore/snapd/blob/master/interfaces/builtin/lxd_support.go#L38

**Comment by htcosta** [comment]
From a adoption perspective, the lack of official packages for other distributions other then Debian/Ubuntu hurts the project i think has this does limits the choices people can make.

Iam using incus on my own projects, and I really like iis feature set and vision, I would love to use this at work also, and can easily build an usecase, the problem is the packaging, has we solely use EL9 and SUSE.
